spring:
  ############################
  ## Oauth2 Setting include
  ############################
  profiles:
    include: oauth

  ######################
  # datasource setting #
  ######################
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3333/sec
    password: 123
    
  ######################
  # JPA setting #
  ######################
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'

############################
## Redis Setting
# docker Set
# docker run -d --name security-redies-db -p 6379:6379 redis --requirepass "123"
############################
  data:
    redis:
      host: localhost
      port: 6379
      password: 123

############################
##Setting Security Log Level
############################
logging:
  level:
    org:
      springframework:
        security:
          web: trace


############################
##Jwt Setting
############################
jwt:
  expiration_time: 350124
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
